sudo: false
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_install:
- openssl aes-256-cbc -K $encrypted_2d2605536f57_key -iv $encrypted_2d2605536f57_iv
  -in keys.tar.gz.enc -out keys.tar.gz -d
- tar xf keys.tar.gz
- export PYTHONPATH=${PYTHONPATH}:$PWD
install: pip install -r android/requirements.txt
script:
- "./android/entry.py"
